# Site settings
title: Jamoma
email: jamoma@jamoma.org
description: > 
  Modular Patching and Programming for Realtime Media.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://jamoma.org" # the base hostname & protocol for your site
twitter_username: jamomaproject
github_username:  jamoma

# Build settings
markdown: kramdown
